name: BedWars
version: 1.0
main: ch.framedev.BedWarsPlugin
api-version: 1.20
author: FrameDev
description: A comprehensive BedWars plugin for Minecraft
softdepend: [CloudNet-Bridge]
libraries:
  - org.xerial:sqlite-jdbc:3.45.0.0

commands:
  bedwars:
    description: Main BedWars command
    usage: /bedwars <join|leave|stats|list|setup|party|queue|vote|cosmetics|achievements>
    aliases: [bw]

permissions:
  bedwars.join:
    description: Allow players to join games
    default: true
  bedwars.leave:
    description: Allow players to leave games
    default: true
  bedwars.stats:
    description: Allow players to view their stats
    default: true
  bedwars.list:
    description: Allow players to list arenas
    default: true
  bedwars.spectate:
    description: Allow players to spectate games
    default: true
  bedwars.setup:
    description: Allow arena setup
    default: op
  bedwars.admin:
    description: Administrative commands
    default: op
  bedwars.bungee:
    description: BungeeCord server switching
    default: true
  bedwars.party:
    description: Party commands
    default: true
  bedwars.party.invite:
    description: Invite players to a party
    default: true
  bedwars.party.kick:
    description: Kick players from a party
    default: true
  bedwars.party.promote:
    description: Promote a party member to leader
    default: true
  bedwars.queue:
    description: Join the map voting queue
    default: true
  bedwars.vote:
    description: Vote for a map
    default: true
  bedwars.vote.admin:
    description: Admin control for map voting
    default: op
  bedwars.cosmetics:
    description: Open cosmetics menu
    default: true
  bedwars.achievements:
    description: Open achievements menu
    default: true
